<?php

namespace ContainerHonmUTi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CtCjB0eService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ctCjB0e' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ctCjB0e'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'reponse' => ['privates', '.errored..service_locator.ctCjB0e.App\\Entity\\Reponse', NULL, 'Cannot autowire service ".service_locator.ctCjB0e": it needs an instance of "App\\Entity\\Reponse" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'reponse' => 'App\\Entity\\Reponse',
        ]);
    }
}
