<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Evenement extends \App\Entity\Evenement implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'date' => [parent::class, 'date', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'eventspeaker' => [parent::class, 'eventspeaker', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'lieu' => [parent::class, 'lieu', null, 16],
        "\0".parent::class."\0".'nbPlace' => [parent::class, 'nbPlace', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'prix' => [parent::class, 'prix', null, 16],
        "\0".parent::class."\0".'reclamations' => [parent::class, 'reclamations', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null, 16],
        'date' => [parent::class, 'date', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'eventspeaker' => [parent::class, 'eventspeaker', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'lieu' => [parent::class, 'lieu', null, 16],
        'nbPlace' => [parent::class, 'nbPlace', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'prix' => [parent::class, 'prix', null, 16],
        'reclamations' => [parent::class, 'reclamations', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'user' => [parent::class, 'user', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
