<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Reclamation extends \App\Entity\Reclamation implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'dateReclamation' => [parent::class, 'dateReclamation', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'evenement' => [parent::class, 'evenement', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'idUser' => [parent::class, 'idUser', null, 16],
        "\0".parent::class."\0".'rate' => [parent::class, 'rate', null, 16],
        "\0".parent::class."\0".'reponses' => [parent::class, 'reponses', null, 16],
        "\0".parent::class."\0".'subject' => [parent::class, 'subject', null, 16],
        'dateReclamation' => [parent::class, 'dateReclamation', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'evenement' => [parent::class, 'evenement', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'idUser' => [parent::class, 'idUser', null, 16],
        'rate' => [parent::class, 'rate', null, 16],
        'reponses' => [parent::class, 'reponses', null, 16],
        'subject' => [parent::class, 'subject', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
