<?php

namespace ContainerG3DMx7i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9SgOnZQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9SgOnZQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9SgOnZQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\ReclamationController::checkEmail' => ['privates', '.service_locator.PqWloHb', 'get_ServiceLocator_PqWloHbService', true],
            'App\\Controller\\ReclamationController::delete' => ['privates', '.service_locator.s8SPndy', 'get_ServiceLocator_S8SPndyService', true],
            'App\\Controller\\ReclamationController::edit' => ['privates', '.service_locator.s8SPndy', 'get_ServiceLocator_S8SPndyService', true],
            'App\\Controller\\ReclamationController::index' => ['privates', '.service_locator.PqWloHb', 'get_ServiceLocator_PqWloHbService', true],
            'App\\Controller\\ReclamationController::new' => ['privates', '.service_locator.cm7n3Ko', 'get_ServiceLocator_Cm7n3KoService', true],
            'App\\Controller\\ReclamationController::show' => ['privates', '.service_locator.SY0zWOw', 'get_ServiceLocator_SY0zWOwService', true],
            'App\\Controller\\ReponseController::delete' => ['privates', '.service_locator.ctCjB0e', 'get_ServiceLocator_CtCjB0eService', true],
            'App\\Controller\\ReponseController::edit' => ['privates', '.service_locator.ctCjB0e', 'get_ServiceLocator_CtCjB0eService', true],
            'App\\Controller\\ReponseController::index' => ['privates', '.service_locator.MCrT8xx', 'get_ServiceLocator_MCrT8xxService', true],
            'App\\Controller\\ReponseController::new' => ['privates', '.service_locator.KerIIiI', 'get_ServiceLocator_KerIIiIService', true],
            'App\\Controller\\ReponseController::show' => ['privates', '.service_locator.Nf.XpWv', 'get_ServiceLocator_Nf_XpWvService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ReclamationController:checkEmail' => ['privates', '.service_locator.PqWloHb', 'get_ServiceLocator_PqWloHbService', true],
            'App\\Controller\\ReclamationController:delete' => ['privates', '.service_locator.s8SPndy', 'get_ServiceLocator_S8SPndyService', true],
            'App\\Controller\\ReclamationController:edit' => ['privates', '.service_locator.s8SPndy', 'get_ServiceLocator_S8SPndyService', true],
            'App\\Controller\\ReclamationController:index' => ['privates', '.service_locator.PqWloHb', 'get_ServiceLocator_PqWloHbService', true],
            'App\\Controller\\ReclamationController:new' => ['privates', '.service_locator.cm7n3Ko', 'get_ServiceLocator_Cm7n3KoService', true],
            'App\\Controller\\ReclamationController:show' => ['privates', '.service_locator.SY0zWOw', 'get_ServiceLocator_SY0zWOwService', true],
            'App\\Controller\\ReponseController:delete' => ['privates', '.service_locator.ctCjB0e', 'get_ServiceLocator_CtCjB0eService', true],
            'App\\Controller\\ReponseController:edit' => ['privates', '.service_locator.ctCjB0e', 'get_ServiceLocator_CtCjB0eService', true],
            'App\\Controller\\ReponseController:index' => ['privates', '.service_locator.MCrT8xx', 'get_ServiceLocator_MCrT8xxService', true],
            'App\\Controller\\ReponseController:new' => ['privates', '.service_locator.KerIIiI', 'get_ServiceLocator_KerIIiIService', true],
            'App\\Controller\\ReponseController:show' => ['privates', '.service_locator.Nf.XpWv', 'get_ServiceLocator_Nf_XpWvService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ReclamationController::checkEmail' => '?',
            'App\\Controller\\ReclamationController::delete' => '?',
            'App\\Controller\\ReclamationController::edit' => '?',
            'App\\Controller\\ReclamationController::index' => '?',
            'App\\Controller\\ReclamationController::new' => '?',
            'App\\Controller\\ReclamationController::show' => '?',
            'App\\Controller\\ReponseController::delete' => '?',
            'App\\Controller\\ReponseController::edit' => '?',
            'App\\Controller\\ReponseController::index' => '?',
            'App\\Controller\\ReponseController::new' => '?',
            'App\\Controller\\ReponseController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ReclamationController:checkEmail' => '?',
            'App\\Controller\\ReclamationController:delete' => '?',
            'App\\Controller\\ReclamationController:edit' => '?',
            'App\\Controller\\ReclamationController:index' => '?',
            'App\\Controller\\ReclamationController:new' => '?',
            'App\\Controller\\ReclamationController:show' => '?',
            'App\\Controller\\ReponseController:delete' => '?',
            'App\\Controller\\ReponseController:edit' => '?',
            'App\\Controller\\ReponseController:index' => '?',
            'App\\Controller\\ReponseController:new' => '?',
            'App\\Controller\\ReponseController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
